_prose.yml
Can only test once merged. Addresses #10
=> add _prose.yml

.travis.yml, README.md, scripts/deploy/deploy.sh, scripts/deploy/deploy_staging.sh, scripts/requirements.txt
Use different versions of the sdg-build package to build different versions of this API
=> matrix builds #13

meta/16-1-1.md, meta/16-1-2.md, meta/16-1-3.md, meta/16-1-4.md, meta/16-10-1.md, meta/16-10-2.md, meta/16-2-1.md, meta/16-2-2.md, meta/16-2-3.md, meta/16-3-1.md, meta/16-3-2.md, meta/16-4-1.md, meta/16-4-2.md, meta/16-5-1.md, meta/16-5-2.md, meta/16-6-1.md, meta/16-6-2.md, meta/16-7-1.md, meta/16-7-2.md, meta/16-8-1.md, meta/16-9-1.md, meta/16-a-1.md, meta/16-b-1.md
Just an experiment at this stage defining indicator sort order within the metadata
=> Investigation - indicator sort order

_prose.yml
Reverts ONSdigital/sdg-data#116
=> Revert "Hide "indicator display order" in Global metadata"

meta/17-1-1.md
=> MAP TEST 2

meta/17-1-1.md
Remove...
data_show_map: true
embedded_map_html: >-
<iframe height="811px" width="100%" src="https://www.ons.gov.uk/visualisations/dvc369/map.html"></iframe>
=> REVERT MAP TEST

data/indicator_3-3-3.csv
Contains additional disaggregations and units column to allow count data and percentages to be displayed.
=> 3.3.3 malaria update

data/indicator_2-3-1.csv
Addition of England LA and Welsh regional data
=> 2.3.1 - update

data/indicator_5-2-1.csv
Simplified version to allow easier use on the tool for users
=> 5.2.1 update

data/indicator_5-2-1.csv
Has a reordering of categories in CSV file
=> 5.2.1 simplified update

data/indicator_5-2-1.csv
Reordered to try and simplify tool
=> 5.2.1 update order

data/indicator_5-2-1.csv
Cannot entirely fix hierarchy issue, think this is the best fix
=> 5.2.1 reordering

data/indicator_2-2-2.csv
2.2.2 data for four countries in UK, plus ethnicity for England, and sex for England and NI
=> 2.2.2 country data

data/indicator_2-2-2.csv, meta/2-1-1.md, meta/2-2-2.md
=> Metadata update

data/indicator_3-b-1.csv
Attempted fix of issue of no data being presented on tool
=> 3.b.1 update

meta/13-1-1.md
Deleted "Indicator:" from indicator title
=> Update 13.1.1 metadata

data/indicator_3-b-1.csv
added units column instead of age category
=> 3.b.1 - attempted data fix

data/indicator_3-b-1.csv
=> 3.b.1 age fix

meta/1-5-1.md
Removed duplicate indicator info from title
=> Update 1.5.1 title

meta/11-5-1.md
=> Update 11.5.1 title

data/indicator_9-1-1.csv
Changed LSOA column name to Local Authority.  Made capitalisation in the road type column consistent
=> 9.1.1 data update

data/indicator_9-1-1.csv
Reorder of columns to put road type first
=> 9.1.1 update

meta/9-1-1.md
=> 9.1.1 metadata update

meta/11-3-1.md, meta/9-1-1.md
Updated with new catch all text about GAP project
=> 9.1.1 and 11.3.1 metadata updates

meta/11-3-1.md, meta/9-1-1.md
Added catch all text link written into indicator file for test
=> 9.1.1 and 11.3.1 metadata update

meta/11-3-1.md
With additional catch all text link and removal of 'none's
=> 11.3.1 metadata update

meta/4-3-1.md
'Percentage of youth (aged 16-24 years) not in education, employment or training'
=> Title updated

meta/17-19-1.md
Changed from not reported to complete
=> 17.19.1 metadata

data/indicator_3-1-1.csv
/ changed to 'or' in chinese or other field in ethnicity column
=> 3.1.1 data update

meta/3-1-1.md
Addition of maternal death definition and catch all text
=> 3.1.1 metadata update

meta/11-6-2.md, meta/11-7-1.md, meta/12-5-1.md, meta/16-1-3.md, meta/16-1-4.md, meta/16-7-1.md, meta/17-8-1.md, meta/2-2-2.md, meta/3-1-1.md, meta/3-2-1.md, meta/3-3-3.md, meta/3-3-4.md, meta/3-4-2.md, meta/4-3-1.md, meta/5-2-1.md, meta/5-b-1.md, meta/7-b-1.md, meta/8-3-1.md, meta/9-1-1.md
Reverts ONSdigital/sdg-data#501
I've reverted this for now - we can decide to reinstate these maps after testing them individually.
=> Revert "Open sdg map"

data/indicator_4-3-1.csv
Fixing errors, making education category a disagg
=> 4.3.1 csv update

meta/4-3-1.md
Changing indicator available and graph title to be more accurate
=> 4.3.1 metadata update

meta/17-19-1.md, meta/17-2-1.md, meta/17-3-2.md
=> Goal 17 metadata updates

meta/17-1-1.md
added 'general' to total government revenue
adjusted graph title and available indicator to reflect this
=> 17.1.1 update

meta/17-1-1.md
Reverts ONSdigital/sdg-data#543
=> Revert "Update 17-1-1.md"

meta/17-1-1.md
Reverts ONSdigital/sdg-data#542
=> Revert "17.1.1 update"

meta/17-8-1.md
This did not display as expected at LA level. Investigating further at https://norric1admin.github.io/sdg-indicators/17-8-1/
=> Remove open-sdg map

meta/16-10-2.md
Testing
in non-statistical indicator text.
=> Non-statistical Indicator text change test

meta/8-5-1.md
8.5.1 source 2 contact details updated and general formatting changes / fixes
=> 8.5.1 metadata update

data/indicator_12-3-1.csv
12.3.1 updated to fix previous commit.
=> 12.3.1 CSV update

data/indicator_17-1-1.csv
Addition of 'revenue' to API script to add these into csv sheet, as per advice from topic expert
=> 17.1.1 renamed columns and categories

meta/12-3-1.md
12.3.1 metadata updated due to data update and minor formatting changes.
=> 12.3.1 metadata update

meta/4-2-1.md
This removes the embed map and switches to the Leaflet (open-sdg) map.
=> 4.2.1 - switch to Leaflet map

data/indicator_8-5-2.csv
Further corrections to the ordering.
=> 8.5.2 CSV ordering update

meta/4-2-1.md
Map tests required - using the 'MAPS' feature branch.
=> Remove Leaflet map (LA boundaries not displaying)

meta/3-2-1.md
=> 3.2.1 metadata update

data/indicator_3-7-1.csv, data/indicator_5-6-1.csv
Removed 'all ages' category from age column to give headline age figures
=> 5.6.1 and 3.7.1 csv with headline age

data/indicator_3-7-1.csv, data/indicator_5-6-1.csv
Removal of extended explanation of 'other methods'
=> 3.7.1 and 5.6.1 csv update

meta/3-7-1.md, meta/5-6-1.md
Addition of extended definition of 'other methods' to footnotes
=> 3.7.1 and 5.6.1 metadata update

data/indicator_3-7-1.csv, data/indicator_5-6-1.csv
Addition of 'including rhythmic method' to all natural family planning categories
=> 3.7.1 and 5.6.1 csv updates

data/indicator_3-7-1.csv, data/indicator_5-6-1.csv
Removal of other methods duplicate names
=> 5.6.1 and 3.7.1 csv update

meta/3-3-2.md
Changed indicator code from 3.3.3 to 3.3.2
=> 3.3.2 metadata update

data/indicator_3-3-2.csv
Added country names, and renamed units so that incidence rate shows up first
=> 3.3.2 csv update

data/indicator_8-6-1.csv
Updated 8.6.1 with disability & headline ¬SA data.
=> 8.6.1 CSV update

meta/8-6-1.md
Fewer definitions, added seasonally adjusted definition.
=> 8.6.1 metadata update

README.md, scripts/deploy/deploy.sh, scripts/deploy/deploy_staging.sh
Fixes #31 
This means that there will always be changes. The time stamp is appended to the README.md before each deploy.
=> Deploy date

data/indicator_3-8-2.csv
=> 3.8.2 csv update

meta/3-a-1.md
=> 3.a.1 metadata update

meta/17-1-1.md
Revised source links that include https:// to attempt to get them to display properly
=> 17.1.1 metadata update

data/indicator_3-9-1.csv
https://github.com/ONSdigital/sdg-indicators/pull/2992
=> Remove 2012 and 2015 (map year slider test)

meta/12-3-1.md
=> 12.3.1 md update

meta/13-b-1.md
=> 13.b.1 md update

data/indicator_13-b-1.csv
moved units column to before value column
=> 13.b.1 csv update

README.md, _prose.yml, scripts/requirements.txt
* Upgrade to sdg-build 0.3.0
* Add translation keys to `_prose.yml` for the reporting_status
* Adds reporting statistics to the output in `/stats` directory.
=> Reporting statistics

meta/5-3-2.md
Change in the calculation feed to remove reference to age
=> 5.3.2 md update

17-18-2.md
Non-statistical with updated catch all text with links to UKSA, OSR and the Code
=> 17.18.2 md

meta/17-18-2.md
Addition of catch all text including links to UKSA, OSR and the Code
=> 17.18.2 md update

meta/17-18-3.md
Addition of catch all text linking to Better Statistics Better Decisions
=> 17.18.3 md update

data/indicator_4-2-2.csv
Note that geocodes have not yet been fixed.
=> 4.2.2 update

meta/12-5-1.md
=> 12.5.1 metadata update

meta/7-2-1.md
Added other information referencing other sources.
=> 7.2.1 metadata update

meta/2-1-1.md
Tweaked catch all text to include 2016 for FAO data
=> 2.1.1 md update

data/indicator_5-3-2.csv
changed years from 2014 format to 2014/15
=> 5.3.2 csv update

data/indicator_9-5-2.csv
Not yet implemented columns removed from CSV
=> 9.5.2 CSV correction

data/indicator_9-5-2.csv
=> 9.5.2 CSV SDMX update

data/indicator_15-7-1.csv, data/indicator_15-c-1.csv
=> 15.c.1 and 15.7.1 csv update

data/indicator_15-7-1.csv, data/indicator_15-c-1.csv
removed pseudo-zeros from butterfly values from 2013-16 as they actually werent counts in these years.
=> 15.7.1 and 15.c.1 csv update

data/indicator_15-7-1.csv
removed unit measure column from csv
=> 15.7.1 csv update

meta/14-1-1.md
Reverts ONSdigital/sdg-data#829
=> Revert "14.1.1 metadata update"

data/indicator_6-2-1.csv, meta/6-2-1.md
6 2 1 update (#911)
* Add files via upload
* Add files via upload
=> PUSH TO LIVE

meta/2-5-1.md
embedded links added to definitions field
=> 2.5.1 2018 update

meta/2-5-1.md
Reverts ONSdigital/sdg-data#939
=> Revert "2.5.1 2018 update"

meta/15-7-1.md, meta/15-c-1.md
Duplicate indicators, so small changes to ensure they are identically displayed
=> 15.7.1 and 15.c.1 alignment

meta/3-4-2.md
Accidentally deleted embedded content when fixing layout so re-adding
=> Added embedded content back to 3.4.2

data/indicator_9-5-2.csv
=> 9.5.2 csv update

meta/9-5-2.md
=> 9.5.2 md udpate

meta/7-2-1.md
catch all text to explain DUKES statistics
=> 7.2.1 md udpate

meta/7-2-1.md
Reverts ONSdigital/sdg-data#1105
=> Revert "7.2.1 md udpate"

meta/7-2-1.md
With tweeked catch all text and addition of link to bridging table
=> 7.2.1 md update

meta/3-1-1.md
Added line about maternal mortality ratio to catch all text
=> 3.1.1 md udpate

data/indicator_2-2-2.csv
corrected NI sex column error. renamed NI to nothern ireland. put all csv values to 2 dp.
=> 2.2.2 csv update

meta/2-5-1.md
=> 2.5.1 md update

data/indicator_10-1-1.csv
Negative numbers removed by script - added back in
=> 10.1.1 CSV update

meta/10-4-1.md
=> 10.4.1 md update

meta/3-4-1.md
=> 3.4.1 md update

meta/9-5-2.md
=> 9.5.2 md update

meta/11-6-2.md
changed title to have PM2.5 as headline
=> 11.6.2 md update

data/indicator_11-6-2.csv
removed PM2.5 labels so it shows as headline
=> 11.6.2 csv update

data/indicator_3-9-1.csv
=> 3.9.1 csv update

meta/3-9-1.md
removed comments and limitations
=> 3.9.1 md update

data/indicator_4-5-1.csv
Slight change to category name
=> 4.5.1 csv update

meta/16-1-2.md
Remove redundant source information
=> 16.1.2 metadata update

meta/4-1-1.md
=> 4.1.1 metadata update

meta/5-b-1.md
=> 5.b.1 md update

meta/5-b-1.md
=> 5.b.1 update

data/indicator_8-10-1.csv
=> 8.10.1 csv update

data/indicator_8-10-1.csv
=> 8.10.1 CSV

data/indicator_3-b-1.csv
=> 3.b.1 csv update

meta/3-b-1.md
removed footnote and added to other info
=> 3.b.1 md update

meta/8-2-1.md
=> 8.2.1 metadata update

meta/12-8-1.md, meta/13-3-1.md, meta/13-a-1.md, meta/13-b-1.md, meta/17-18-2.md, meta/17-19-2.md, meta/4-7-1.md, meta/5-6-2.md
https://github.com/ONSdigital/sdg-indicators/issues/3088
=> Make site links descriptive

meta/4-5-1.md
Missed the indicator available field update
=> 4.5.1 metadata update

meta/3-4-2.md
Reverts ONSdigital/sdg-data#1488
=> Revert "Added embed and turned off map"

data/indicator_9-2-2.csv
Changed nationality and country of birth to include 'nationality' and 'country of birth' in the label.
=> 9.2.2 label fix

data/indicator_9-2-2.csv, meta/16-6-2.md
Fix 16.6.2 to have a 1 to 10 Y axis.
=> 16.6.2 1 to 10 update

meta/9-b-1.md
Reverts ONSdigital/sdg-data#1575
=> Revert "9.b.1 metadata update"

meta/1-4-2.md
Mark as 'Exploring data sources'
=> 1.4.2 metadata update

meta/12-7-1.md
Added link to Procurement Reform (Scotland) Act 2014.
=> 12.7.1 update

data/indicator_6-3-2.csv
=> 6.3.2 csv update

meta/12-1-1.md
Reverts ONSdigital/sdg-data#1669
=> Revert "12.1.1 metadata update"

meta/16-1-1.md
=> 16.1.1 metadata update

data/indicator_3-b-1.csv, meta/3-b-1.md
Reverts ONSdigital/sdg-data#1811
=> Revert "3 b 1"

data/indicator_16-3-2.csv, meta/16-3-2.md
Reverts ONSdigital/sdg-data#1900
=> Revert "16 3 2update"

data/indicator_16-1-3.csv, meta/16-1-3.md
Reverts ONSdigital/sdg-data#1921
=> Revert "16-1-3"

data/indicator_9-c-1.csv, meta/9-c-1.md
* Add files via upload
* Add files via upload
* Add files via upload
* 9-c-1 data
* 9-c-1 meta
Co-authored-by: McCraeJames <54808271+McCraeJames@users.noreply.github.com>
=> 9 c 1 (#2020)

meta/17-18-1.md
Changed the data to numeric and removed formulas to see if it will solve the problem
=> 17-18-1 csv edited

README.md
This is the same as Matt's original pull request. I closed it and now recreating as there is no way around it
=> Updating readme... again

meta/5-5-1.md
@EmmaWoodONS I just seen your email re so had a quick look - just from the top of my head these changes might help:
- There seemed to be an empty white space right at the start of the file (from my experience this has happened a couple of times when I've edited an md file directly but not sure why it happens
- `graph_stacked_disaggregation` needs to match the column name exactly so `Sex` rather than `Sex`
=> Remove empty space and rename stacked disagg

meta/17-11-1.md
Manual correction of url check
=> 17-11-1 md link

meta/1-2-1.md
adding correction notice to 15-5-1
=> push-to-live

data/indicator_17-11-1.csv, meta/17-11-1.md
Updating indicator with latest data point for 2019
=> 17-11-1 update

scripts/build_data.py, scripts/check_data.py, scripts/requirements.txt
Reverts ONSdigital/sdg-data#2463
=> Revert "Auto-generate tier, metadata link and metadata link text"

config_data.yml, scripts/requirements.txt
=> 1.3.0 upgrade

meta/11-4-1.md
Setting the required disaggregation to "Type of expenditure", so it is correctly picked up by NRP (a work-around method)
=> 2020-11.4.1-md disaggregation test

meta/4-a-1.md, meta/4-c-1.md
Testing with a dummy required disaggregations to check if NRP will pick up as fully disaggregated (Units doesn't work)
=> 2020-4.c.1 md disaggregation test

data/indicator_17-3-1.csv, meta/17-3-1.md
=> 17-3-1 update

data/indicator_17-2-1.csv, meta/17-2-1.md
Reverts ONSdigital/sdg-data#2524 (correction of a typo, so need to re-merge the corrected feature branch for another preview)
=> Revert "17 2 1 preview"

data/indicator_17-2-1.csv, meta/17-2-1.md
Reverts ONSdigital/sdg-data#2526
=> Revert "17 2 1 preview II"

data/indicator_3-d-2.csv, meta/3-d-2.md
Reverts ONSdigital/sdg-data#2547
=> Revert "3 d 2"

meta/17-13-1.md
=> 17-13-1-md update

data/indicator_16-1-1.csv, meta/16-1-1.md
Reverts ONSdigital/sdg-data#2551
=> Revert "16 1 1"

data/indicator_15-b-1.csv, meta/15-b-1.md
Reverts ONSdigital/sdg-data#2565
=> Revert "15.b.1 for preview"

README.md, data/indicator_15-b-1.csv, meta/15-b-1.md
Reverts ONSdigital/sdg-data#2581
=> Revert "15.b.1"

README.md, data/indicator_15-b-1.csv, meta/15-b-1.md
Reverts ONSdigital/sdg-data#2584
=> Revert "15.b.1 preview"

data/indicator_17-6-1.csv, meta/17-6-1.md
Reverts ONSdigital/sdg-data#2590
=> Revert "17.6.1 preview"

data/indicator_3-5-1.csv, meta/3-5-1.md
Reverts ONSdigital/sdg-data#2592
=> Revert "3 5 1"

data/indicator_3-3-5.csv, meta/3-3-5.md
Reverts ONSdigital/sdg-data#2602
=> Revert "3 3 5"

data/indicator_15-7-1.csv
Reverts ONSdigital/sdg-data#2607
=> Revert "15-7-1"

data/indicator_15-7-1.csv, meta/15-7-1.md
Reverts ONSdigital/sdg-data#2606
=> Revert "15 7 1"

data/indicator_17-1-1.csv, meta/17-1-1.md
Reverts ONSdigital/sdg-data#2597
=> Revert "17.1.1 preview"

data/indicator_6-2-1.csv, meta/6-2-1.md
Updated csv disaggregations to a logical order (Atanaska)
=> Feature 6 2 1

data/indicator_16-1-4.csv, meta/16-1-4.md
Reverts ONSdigital/sdg-data#2736
=> Revert "Feature 16 1 4 maps"

data/indicator_1-a-2.csv, meta/1-a-2.md
Reverts ONSdigital/sdg-data#2749
=> Revert "Feature 1 a 2" - TE sign off needed

data/indicator_17-8-1.csv
=> Feature 17 8 1

data/indicator_1-1-1.csv, data/indicator_1-a-2.csv, meta/1-1-1.md, meta/1-a-2.md
Queries spreadsheet CSV and md updates for 1-1-1 and 1-a-2
=> feature-1-1-1

meta/1-1-1.md
Reverts ONSdigital/sdg-data#2876
=> Revert "Update 1-1-1.md"

data/indicator_12-b-1.csv, meta/12-b-1.md
=> Feature 12 b 1 update 2 1

data/indicator_16-5-2.csv, meta/16-5-2.md
Reverts ONSdigital/sdg-data#2992
=> Revert "Feature 16 5 2"

data/indicator_16-5-2.csv
Reverts ONSdigital/sdg-data#2987
=> Revert "indicator-16-5-2"

data/indicator_16-5-1.csv
Reverts ONSdigital/sdg-data#2986
=> Revert "indicator_16-5-1"

data/indicator_10-2-1.csv
=> 10-2-1 csv

meta/16-b-1.md
Update to include y axis does not always go to 100% footbote
=> Feature 16 b 1 y axis

meta/16-8-1.md
Update to include "y axis not always to 100%" footnote
=> Feature 16 8 1 y axis

indicator_16-7-1.csv, meta/16-7-1.md
including y axis not always to 100% footnote
=> Feature 16 7 1 y axis

meta/16-1-3.md
including y axis not always 100% footnote
=> Feature 16 1 3 y axis

data/indicator_5-2-2.csv, meta/5-2-2.md
include y axis does not always equal 100% footnote
=> Feature 5 2 2 y axis

data/indicator_10-4-1.csv
=> 10-4-1 csv

data/indicator_10-2-1.csv, meta/10-2-1.md
=> Feature 10 2 1

meta/10-6-1.md
=> 10-6-1 md yaxis

data/indicator_5-5-1.csv, meta/5-5-1.md
Reverts ONSdigital/sdg-data#3117
=> Revert "5-5-1"

data/indicator_5-3-2.csv, meta/5-3-2.md
Reverts ONSdigital/sdg-data#3102
=> Revert "Feature 5 3 2"

data/indicator_3-4-2.csv, meta/3-4-2.md
=> Feature 3 4 2

data/indicator_12-4-2.csv, meta/12-4-2.md
Reverts ONSdigital/sdg-data#3228
=> Revert "Feature 12 4 2"

data/indicator_12-4-1.csv, meta/12-4-1.md
Reverts ONSdigital/sdg-data#3248
=> Revert "Feature 12 4 1"

data/indicator_3-7-2.csv, meta/3-7-2.md
Reverts ONSdigital/sdg-data#3024
=> Revert "Feature 3 7 2"

data/indicator_8-4-1.csv, meta/8-4-1.md
=> Feature 8 4 1

data/indicator_8-4-1.csv, meta/8-4-1.md
Reverts ONSdigital/sdg-data#3277
=> Revert "8-4-1"

data/indicator_8-4-2.csv, meta/8-4-2.md
Reverts ONSdigital/sdg-data#3278
=> Revert "Feature 8 4 2"

meta/8-4-1.md
Reverts ONSdigital/sdg-data#3290
=> Revert "Feature 8 4 1"

config_data.yml, scripts/requirements.txt
http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-2.1.0/
=> Feature 2.1.0

data/indicator_8-4-2.csv, meta/8-4-2.md
=> Feature 8 4 2

data/indicator_5-6-1.csv, meta/5-6-1.md
The automation QA checks flagged up a few cells that had the wrong data on the live site, this corrects those
=> Feature 5 6 1

scripts/build_data.py
http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-release-text/
=> Source Release Text Update

data/indicator_10-a-1.csv
Change "Country Group" to sentence case to align with data dictionary
=> 10-a-1 csv minor capitalisation fix

meta/2-2-1.md
Reverts ONSdigital/sdg-data#3475
=> Revert "Feature 2 2 1"

config_data.yml, scripts/requirements.txt
merge this one before the site one
=> Feature 2.2.0 upgrade

meta/16-b-1.md
Minor metadata change to say that 2023 data may not be available
=> Feature 16 b 1

meta/17-18-3.md
Reverts ONSdigital/sdg-data#3590
=> Revert "Feature 17 18 3" from develop
